name: Docs

on:
  push:
    branches:
      - master

concurrency: 
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/shared-workflows-lint.yml
    with:
      skip-docs: true

  publish:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
      - name: Cache Yarn
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-packages-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-
      - name: Yarn
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - name: Build Packages with SWC
        run: yarn build:dev
      - name: Build Docs
        run: yarn build:docs
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: src/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
