name: Publish

on:
  push:
    branches:
      - master
      - support/*

concurrency: 
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/shared-workflows-lint.yml
    with:
      skip-docs: true

  info:
    uses: ./.github/workflows/shared-workflows-info.yml

  publish:
    needs: [info, lint]
    if: needs.info.outputs.beta == 'false' && needs.info.outputs.skip-publish != 'true'
    uses: ./.github/workflows/shared-workflows-publish.yml
    with: 
      version: ${{ needs.info.outputs.version }}
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      DISCORD_RELEASE_WEBHOOK_ID: ${{ secrets.DISCORD_RELEASE_WEBHOOK_ID }}
      DISCORD_RELEASE_WEBHOOK_TOKEN: ${{ secrets.DISCORD_RELEASE_WEBHOOK_TOKEN }}