name: Request For Comments

on: 
  project_card: 
    types: ["created", "moved", "converted", "edited"]

concurrency: 
  group: rfc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  request-for-comments:
    runs-on: ubuntu-latest
    if: github.event.project_card.column_id == 13280674 && !!github.event.project_card.content_url
    steps:
      - name: Node
        uses: actions/setup-node@v3
      - name: Get Issue Url
        id: issue-url
        run: echo 'URL='$(node -p -e "'${{ github.event.project_card.content_url }}'.replace('https://api.github.com/repos', 'https://github.com')") >> $GITHUB_OUTPUT
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_RFC_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_RFC_WEBHOOK_TOKEN }}
          args: "RFC: ${{ steps.issue-url.outputs.URL }}"