name: Request For Comments

on: 
  project_card: 
    types: ["created", "moved", "converted", "edited"]

jobs:
  request-for-comments:
    runs-on: ubuntu-latest
    if: github.event.project_card.column_id == 13280674 && !!github.event.project_card.content_url
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Get Issue Url
        id: issue-url
        run: echo '::set-output name=URL::'$(node -p -e "'${{ github.event.project_card.content_url }}'.replace('https://api.github.com/repos', 'https://github.com')")
      - name: Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_RFC_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_RFC_WEBHOOK_TOKEN }}
          args: "RFC: ${{ steps.issue-url.outputs.URL }}"