name: zSharedWorkflowsLint

on:
  workflow_call:
    inputs:
      skip-docs:
        type: boolean
        required: false
        default: false

jobs:
  lint:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
      - name: Cache Yarn
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-packages-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-
      - name: Yarn
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Build
        shell: bash
        run: yarn build
      - name: Build Docs
        if: ${{ inputs.skip-docs == 'false' }}
        run: yarn build:docs